"""
Database configuration and ORM models.

This module provides:
- SQLAlchemy engine/session setup for SQLite (dev)
- The `PipelineRun` table for tracking pipeline state
- `create_all()` which can be called during FastAPI startup
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Generator

from sqlalchemy import DateTime, Float, String, create_engine, Integer, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, sessionmaker

from .config import settings


class Base(DeclarativeBase):
    """Declarative base for SQLAlchemy ORM."""


class PipelineRun(Base):
    """
    Tracks lifecycle and outcome of a pipeline execution.

    Attributes:
        run_id: Unique identifier for the pipeline run.
        building_id: Building identifier tied to the run.
        status: queued | running | completed | failed (string-based for flexibility)
        created_at: UTC creation timestamp.
        completed_at: UTC completion timestamp (nullable while running).
        duration_s: Total duration seconds (nullable while running).
        error_msg: Error message for failed runs (nullable).
    """

    __tablename__ = "pipeline_runs"

    run_id: Mapped[str] = mapped_column(String, primary_key=True)
    building_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    status: Mapped[str] = mapped_column(String, nullable=False, index=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    duration_s: Mapped[float | None] = mapped_column(
        Float,
        nullable=True,
    )
    error_msg: Mapped[str | None] = mapped_column(
        String,
        nullable=True,
    )


class AgentOutput(Base):
    """
    Stores JSON output generated by each agent.
    """
    __tablename__ = "agent_outputs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    agent_name: Mapped[str] = mapped_column(String, nullable=False)
    output_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )


class Recommendation(Base):
    """
    Individual actionable optimization recommendation.
    """
    __tablename__ = "recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    category: Mapped[str] = mapped_column(String, nullable=False)
    action: Mapped[str] = mapped_column(String, nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    expected_impact: Mapped[str] = mapped_column(String, nullable=False)
    priority_score: Mapped[float] = mapped_column(Float, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )


class AnomalyLog(Base):
    """
    Recorded anomaly details detected by the performance analyzer.
    """
    __tablename__ = "anomaly_logs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    parameter: Mapped[str] = mapped_column(String, nullable=False)
    severity: Mapped[str] = mapped_column(String, nullable=False)
    root_cause: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)


class ForecastResult(Base):
    """
    Metadata and tracking metrics for demand forecasts.
    """
    __tablename__ = "forecast_results"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    run_id: Mapped[str] = mapped_column(String, index=True, nullable=False)
    horizon_hours: Mapped[int] = mapped_column(Integer, nullable=False)
    model_used: Mapped[str] = mapped_column(String, nullable=False)
    mape: Mapped[float] = mapped_column(Float, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )


_connect_args = {}
if settings.DATABASE_URL.startswith("sqlite"):
    # Required for SQLite usage from FastAPI threads.
    _connect_args = {"check_same_thread": False}

engine = create_engine(
    settings.DATABASE_URL,
    connect_args=_connect_args,
    future=True,
)

SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)


def create_all() -> None:
    """
    Create all database tables.

    Call this during FastAPI startup using the application's lifespan.
    """

    Base.metadata.create_all(bind=engine)


def get_db_session() -> Generator:
    """
    FastAPI dependency helper yielding a SQLAlchemy session.

    Yields:
        A SQLAlchemy session instance.
    """

    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

